master:
    image: ros:noetic-ros-core-focal
    container_name: master
    command:
        - roscore

gazebo_publisher:
    image: gazebo:libgazebo11-focal 
    container_name: gazebo_publisher
    environment:
        - "ROS_HOSTNAME=gazebo_publisher"
        - "ROS_MASTER_URI=http://master:11311"
    command: source /gzserver_entrypoint.sh
