include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

stages:
  - build

build-dbw-node-firmware:
  image:
    name: git-registry.cooperigvc.org/igvc/selfdrive/dbw/node_fw:latest
    entrypoint: [ '/bin/sh', '-c' ]
  stage: build
  script:
    - cd dbw/node_fw
    - pio run
  artifacts:
    paths:
      - dbw/node_fw/.pio/build/*/firmware.{bin,elf}
