master:
    image: ros:noetic-ros-core-focal
    container_name: master
    command:
        - roscore

gazebo_publisher:
    image: gazebo:gzserver11-focal 
    container_name: gazebo_publisher
    ports:
        - "8000:8000"
    environment:
        - "ROS_MASTER_URI=http://master:11311"
        - "ROS_HOSTNAME=gazebo_publisher"
          #command: 
    #- run -d -v="/tmp/.gazebo/:/root/.gazebo/" --name=gazebo gazebo
    #- docker exec -it gazebo bash     
    #command: source /gzserver_entrypoint.sh

