version: '3'

services:
    master:
        image: ros:noetic-ros-core-focal
        container_name: master
        tty: true
        environment:
        - 'ROS_HOSTNAME=master'
        - 'ROS_MASTER_URI=http://master:11311'
          #restart: unless-stopped
        command: stdbuf -o L roscore

    gazebo_publisher:
        image: gazebo:gzserver11-focal 
        container_name: gazebo_publisher
        tty: true
        ports:
        - "11345:11345"
        environment:
        - "ROS_HOSTNAME=gazebo_publisher"
        - "ROS_MASTER_URI=http://master:11311"
        command: gzserver
        #roslaunch gazebo_ros empty_world.launch
