# https://docs.docker.com/compose/gpu-support/
version: '3'

services:
    master:
        image: ros:noetic-ros-core-focal
        container_name: master
        tty: true
        environment:
            - 'ROS_HOSTNAME=master'
            - 'ROS_MASTER_URI=http://master:11311'
        restart: unless-stopped
        command: stdbuf -o L roscore

    rplidar:
        build: docker-rplidar/.
        container_name: rplidar
        tty: true
        environment:
            - 'ROS_HOSTNAME=rplidar'
            - 'ROS_MASTER_URI=http://master:11311'
        devices:
            - '/dev/ttyUSB0:/dev/ttyUSB0'
        command: roslaunch rplidar_ros rplidar.launch
        depends_on:
            - master

    zed-ros:
        build: docker-zed/.
        container_name: zed
        tty: true
        environment:
            - 'ROS_HOSTNAME=zed'
            - 'ROS_MASTER_URI=http://master:11311'
        devices:
            - '/dev/ttyUSB0:/dev/ttyUSB0'
        command: roslaunch zed_wrapper zed.launch
        depends_on:
            - master
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]