version: '3'

services:
    master:
        image: ros:noetic-ros-core-focal
        container_name: master
        tty: true
        environment:
            - 'ROS_HOSTNAME=master'
            - 'ROS_MASTER_URI=http://master:11311'
        restart: unless-stopped
        command: stdbuf -o L roscore

    rplidar:
        build: docker-rplidar/.
        container_name: rplidar
        tty: true
        environment:
            - 'ROS_HOSTNAME=rplidar'
            - 'ROS_MASTER_URI=http://master:11311'
        devices:
            - '/dev/ttyUSB0:/dev/ttyUSB0'
        command: roslaunch rplidar_ros rplidar.launch
        depends_on:
            - master
    
    gzserver:
        build: docker-gzserver/.
        container_name: gzserver
        tty: true
        environment:
            - 'ROS_HOSTNAME=gzserver'
            - 'ROS_MASTER_URI=http://master:11311'
        ports:
            - '11345:11345'
        command: roslaunch gazebo_ros empty_world.launch
        restart: unless-stopped
        depends_on:
            - master